# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2


before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./src
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - dist/cosign.pub

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - id: cosign
    cmd: cosign
    signature: "${artifact}.sig"
    artifacts: all
    args:
      - "sign-blob"
      - "--key=env://COSIGN_PRIVATE_KEY"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"


release:
  extra_files:
    - glob: dist/cosign.pub

homebrew_casks:
  -
    name: anonymongo
    repository:
      owner: yuvalherziger
      name: homebrew-anonymongo
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleasrbot
      email: bot@goreleaser.com
    description: "A CLI tool to redact sensitive values from MongoDB log files"
    homepage: "https://github.com/yuvalherziger/homebrew"
    license: "MIT"
    caveats: "To test the installation, run: anonymongo version"
