package main

type OperatorType int

const (
	Pipeline   OperatorType = iota // A nested pipeline
	Exempt     OperatorType = iota // No need to redact exempted keys
	Redactable OperatorType = iota // Redact based on existing rules
	FieldName  OperatorType = iota // Redact if eager redaction is used
)

var KnownOperators = map[string]interface{}{
	"$addFields": Redactable,
	"$bucket": map[string]interface{}{
		"boundaries": Redactable,
		"default":    Redactable,
		"output":     Redactable,
		"groupBy":    Redactable,
	},
	"$bucketAuto": map[string]interface{}{
		"granularity": Redactable,
		"output":      Redactable,
		"buckets":     Redactable,
		"groupBy":     Redactable,
	},
	"$changeStream": map[string]interface{}{
		"allChangesForCluster":     Redactable,
		"fullDocument":             Redactable,
		"fullDocumentBeforeChange": Redactable,
		"resumeAfter":              Redactable,
		"showExpandedEvents":       Redactable,
		"startAfter":               Redactable,
		"startAtOperationTime":     Redactable,
	},
	"$changeStreamSplitLargeEvent": Redactable,
	"$collStats": map[string]interface{}{
		"latencyStats":   Redactable,
		"storageStats":   Redactable,
		"count":          Redactable,
		"queryExecStats": Redactable,
	},
	"$count": FieldName,
	"$currentOp": map[string]interface{}{
		"allUsers":        Redactable,
		"idleConnections": Redactable,
		"idleCursors":     Redactable,
		"idleSessions":    Redactable,
		"localOps":        Redactable,
	},
	"$densify": map[string]interface{}{
		"field":             Redactable,
		"partitionByFields": Redactable,
		"range":             Redactable,
	},
	"$documents": Redactable,
	"$facet":     Pipeline,
	"$fill": map[string]interface{}{
		"partitionByFields": Redactable,
		"partitionBy":       Redactable,
		"sortBy":            Redactable,
		"output":            Redactable,
	},
	"$geoNear": map[string]interface{}{
		"distanceField":      Redactable,
		"distanceMultiplier": Redactable,
		"includeLocs":        Redactable,
		"key":                Redactable,
		"maxDistance":        Redactable,
		"minDistance":        Redactable,
		"near":               Redactable,
		"query":              Redactable,
		"spherical":          Redactable,
	},
	"$graphLookup": map[string]interface{}{
		"from":                    Exempt,
		"startWith":               Redactable,
		"connectFromField":        Redactable,
		"connectToField":          Redactable,
		"as":                      Redactable,
		"maxDepth":                Redactable,
		"depthField":              Redactable,
		"restrictSearchWithMatch": Redactable,
	},
	// TODO: Stopped here:
	"$group":      Redactable,
	"$indexStats": Redactable,
	"$limit":      Exempt,
	"$listLocalSessions": map[string]interface{}{
		"users":    Redactable,
		"allUsers": Redactable,
	},
	"$listSampledQueries": map[string]interface{}{"namespace": nil},
	"$listSearchIndexes": map[string]interface{}{
		"id":   Redactable,
		"name": Redactable,
	},
	"$listSessions": map[string]interface{}{
		"users":    Redactable,
		"allUsers": Redactable,
	},
	"$lookup": map[string]interface{}{
		"from":         Exempt,
		"localField":   Redactable,
		"foreignField": Redactable,
		"let":          Redactable,
		"pipeline":     Pipeline,
		"as":           Exempt,
	},
	"$match": Redactable,
	"$merge": map[string]interface{}{
		"into":           Exempt,
		"on":             Redactable,
		"let":            Redactable,
		"whenMatched":    Exempt,
		"whenNotMatched": Exempt,
	},
	"$out": map[string]interface{}{
		"db":         Exempt,
		"coll":       Exempt,
		"timeseries": Exempt,
	},
	"$planCacheStats": Exempt,
	"$project":        Redactable,
	"$querySettings":  Exempt,
	"$queryStats":     Exempt,
	"$redact":         Redactable,
	"$replaceRoot":    map[string]interface{}{"newRoot": nil},
	"$replaceWith":    Redactable,
	"$sample":         Exempt,
	"$search":         Redactable, // TODO
	"$searchMeta":     Redactable, // TODO
	"$set":            Redactable,
	"$setWindowFields": map[string]interface{}{
		"partitionBy": Redactable,
		"sortBy":      Redactable,
		"output":      Redactable,
		"window":      Redactable,
	},
	"$shardedDataDistribution": Exempt,
	"$skip":                    Exempt,
	"$sort":                    Redactable,
	"$sortByCount":             Redactable,
	"$unionWith": map[string]interface{}{
		"coll":     Redactable,
		"pipeline": Pipeline,
	},
	"$unset": Redactable,
	// Handle cases where the $unoperator is not a string
	"$unwind":        Redactable,
	"$vectorSearch":  Redactable, // TODO
	"$eq":            Redactable,
	"$gt":            Redactable,
	"$gte":           Redactable,
	"$in":            Redactable,
	"$lt":            Redactable,
	"$lte":           Redactable,
	"$ne":            Redactable,
	"$nin":           Redactable,
	"$and":           Redactable,
	"$not":           Redactable,
	"$nor":           Redactable,
	"$or":            Redactable,
	"$exists":        Redactable,
	"$type":          Redactable,
	"$expr":          Redactable,
	"$jsonSchema":    Redactable,
	"$mod":           Redactable,
	"$regex":         Redactable,
	"$text":          Redactable,
	"$where":         Redactable,
	"$geoIntersects": Redactable,
	"$geoWithin":     Redactable,
	"$near":          Redactable,
	"$nearSphere":    Redactable,
	"$all":           Redactable,
	"$elemMatch":     Redactable,
	"$size":          Redactable,
	"$bitsAllClear":  Redactable,
	"$bitsAllSet":    Redactable,
	"$bitsAnyClear":  Redactable,
	"$bitsAnySet":    Redactable,
	"$meta":          Redactable,
	"$slice":         Redactable,
	"$rand":          Redactable,
	"$natural":       Redactable,
	"$currentDate":   Redactable,
	"$inc":           Redactable,
	"$min":           Redactable,
	"$max":           Redactable,
	"$mul":           Redactable,
	"$rename":        Redactable,
	"$setOnInsert":   Redactable,
	"$addToSet":      Redactable,
	"$pop":           Redactable,
	"$pull":          Redactable,
	"$push":          Redactable,
	"$pullAll":       Redactable,
	"$each":          Redactable,
	"$position":      Redactable,
	"$bit":           Redactable,
	"$abs":           Redactable,
	"$add":           Redactable,
	"$ceil":          Redactable,
	"$divide":        Redactable,
	"$exp":           Redactable,
	"$floor":         Redactable,
	"$ln":            Redactable,
	"$log":           Redactable,
	"$log10":         Redactable,
	"$multiply":      Redactable,
	"$pow":           Redactable,
	"$round":         Redactable,
	"$sqrt":          Redactable,
	"$subtract":      Redactable,
	"$trunc":         Redactable,
	"$arrayElemAt":   Redactable,
	"$arrayToObject": Redactable,
	"$concatArrays":  Redactable,
	"$filter":        Redactable,
	"$firstN":        Redactable,
	"$indexOfArray":  Redactable,
	"$isArray":       Redactable,
	"$lastN":         Redactable,
	"$map":           Redactable,
	"$maxN":          Redactable,
	"$minN":          Redactable,
	"$objectToArray": Redactable,
	"$range":         Redactable,
	"$reduce":        Redactable,
	"$reverseArray":  Redactable,
	"$sortArray":     Redactable,
	"$zip":           Redactable,
	"$cmp":           Redactable,
	"$oid":           Redactable,
	"$date":          Redactable,
	"$cond":          Redactable,
	"if":             Redactable,
	"then":           Redactable,
	"else":           Redactable,
}
