name: Vulnerabilities Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: WriteGoList
        run: go list -json -deps ./src/... > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
