name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          # Exclude invalid OS/GOOS combinations
          - os: ubuntu-latest
            goos: darwin
          - os: ubuntu-latest
            goos: windows
          - os: macos-latest
            goos: linux
          - os: macos-latest
            goos: windows
          - os: windows-latest
            goos: linux
          - os: windows-latest
            goos: darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          mkdir -p dist
          name="anonymongo"
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            ext=".exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "dist/${name}-${{ matrix.goos }}-${{ matrix.goarch }}${ext}" ./src
        shell: bash

      - name: Upload binaries to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          name: anonymongo-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/
